"""Check both real NBI endpoints; optionally verify isolated Context databases."""
from __future__ import annotations

import argparse
import json
import urllib.request
import uuid


def call(base: str, path: str, method: str = 'GET', body=None):
    data = None if body is None else json.dumps(body).encode()
    req = urllib.request.Request(base.rstrip('/') + path, data=data, method=method,
                                 headers={'Content-Type': 'application/json'})
    with urllib.request.urlopen(req, timeout=30) as response:
        raw = response.read()
        return json.loads(raw) if raw else None


def context_ids(base: str) -> set[str]:
    payload = call(base, '/tfs-api/contexts')
    if not isinstance(payload, dict) or not isinstance(payload.get('contexts'), list):
        raise ValueError(f'{base}: unexpected ContextList response')
    return {item['context_id']['context_uuid']['uuid'] for item in payload['contexts']}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--sat-a', default='http://127.0.0.1:18080')
    parser.add_argument('--sat-b', default='http://127.0.0.1:18081')
    parser.add_argument('--check-isolation', action='store_true',
                        help='Create and remove one temporary Context on SAT-A; require it absent on SAT-B.')
    args = parser.parse_args()
    for label, base in [('SAT-A', args.sat_a), ('SAT-B', args.sat_b)]:
        call(base, '/healthz')
        print(f'{label}: healthz OK; {len(context_ids(base))} contexts')
    if args.check_isolation:
        identifier = str(uuid.uuid4())
        probe = {'context_id': {'context_uuid': {'uuid': identifier}},
                 'name': 'migration-isolation-probe'}
        try:
            call(args.sat_a, '/tfs-api/contexts', 'POST', {'contexts': [probe]})
            if identifier not in context_ids(args.sat_a):
                raise RuntimeError('Created context cannot be read back from SAT-A')
            if identifier in context_ids(args.sat_b):
                raise RuntimeError('SAT-B already sees the context: state is shared')
            print('Context isolation verified: probe exists only on SAT-A')
        finally:
            # This UUID was generated by this invocation; never remove existing user contexts.
            if identifier in context_ids(args.sat_a):
                call(args.sat_a, '/tfs-api/context/' + identifier, 'DELETE')


if __name__ == '__main__':
    main()
